### ISSUE TITLE
Refill Calling Parameters in Form After Validation

### ISSUE THREAD

**Issue by init-dcat-ap-de** [ISAITB/shacl-validator#3]
See https://github.com/GovDataOfficial/DCAT-AP.de-SHACL-Validation/issues/15:

> When invoking the validator, we have to fill all form fields.
> 
> When submitting the form multiple times (e.g. to try multiple validation rules or to revalidate a dataset) why not fill in the parameters in the form fields again?

And the following discussion.

**Comment by costas80** [comment]
This is indeed a good suggestion and one that should be easy to support. We'll get started on this and let you know what its available.

**Comment by costas80** [comment]
The validator has been adapted to retain all submitted form inputs so that you can immediately trigger a new validation from the results' display. The minimal UI configuration for the validator has also been adapted to retain the submitted inputs when clicking on the result page's "Back" button.

The update is now live and ready to use.
